# Generated by Django 5.1.7 on 2025-04-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='catigory',
            field=models.CharField(choices=[('comedy', 'comedy'), ('action', 'action'), ('romas', 'romas')], default='comedy', max_length=60),
        ),
    ]
