# Generated by Django 5.1.7 on 2025-04-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_list_delete_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
