# Generated by Django 5.1.7 on 2025-04-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_remove_film_list_date_time_remove_film_list_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parties',
            name='image',
        ),
        migrations.AddField(
            model_name='film_list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
