# Generated by Django 5.1.7 on 2025-04-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_remove_parties_image_film_list_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film_list',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Crime', 'Crime'), ('Historical', 'Historical'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('War', 'War'), ('Sports', 'Sports')], max_length=100),
        ),
    ]
