# Generated by Django 5.1.7 on 2025-04-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_film_list_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_list',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
