# Generated by Django 5.1.7 on 2025-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_film_list_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_list',
            name='id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
